# frozen_string_literal: true

require 'pathname'
require 'open3'

desc 'build a function file'
task :build, [:f] do |f: '*'|
  Pathname.glob("#{f}.yml").each do |file|
    sh 'faas-cli', 'build', '-f', file.to_s
  end
end

desc 'publish a function file'
task :publish, [:f] => :build do |f: '*'|
  Pathname.glob("#{f}.yml").each do |file|
    sh 'faas-cli', 'publish', '-f', file.to_s, '--platforms', 'linux/arm64,linux/arm,linux/amd64'
  end
end
